// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: temporal/yieldmos/delegation_timestamp.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DelegationTimestamp struct {
	Timestamp time.Time  `protobuf:"bytes,1,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	Balance   types.Coin `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance"`
}

func (m *DelegationTimestamp) Reset()         { *m = DelegationTimestamp{} }
func (m *DelegationTimestamp) String() string { return proto.CompactTextString(m) }
func (*DelegationTimestamp) ProtoMessage()    {}
func (*DelegationTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_241987de12034dd1, []int{0}
}
func (m *DelegationTimestamp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegationTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegationTimestamp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegationTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegationTimestamp.Merge(m, src)
}
func (m *DelegationTimestamp) XXX_Size() int {
	return m.Size()
}
func (m *DelegationTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegationTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_DelegationTimestamp proto.InternalMessageInfo

func (m *DelegationTimestamp) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

func (m *DelegationTimestamp) GetBalance() types.Coin {
	if m != nil {
		return m.Balance
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*DelegationTimestamp)(nil), "temporal.yieldmos.DelegationTimestamp")
}

func init() {
	proto.RegisterFile("temporal/yieldmos/delegation_timestamp.proto", fileDescriptor_241987de12034dd1)
}

var fileDescriptor_241987de12034dd1 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0xe3, 0x4f, 0x9f, 0xf8, 0x09, 0x13, 0x81, 0xa1, 0x64, 0x70, 0x10, 0x13, 0x03, 0x1c,
	0xab, 0x20, 0x06, 0xd6, 0xc0, 0x0c, 0x52, 0xd5, 0x89, 0x05, 0xd9, 0xe9, 0xc1, 0x58, 0x24, 0x39,
	0x51, 0xe2, 0x02, 0xbd, 0x8b, 0x0e, 0x5c, 0x54, 0xc7, 0x8e, 0x4c, 0x80, 0x92, 0x1b, 0x41, 0xf9,
	0xad, 0xc4, 0x66, 0xeb, 0x7d, 0xfc, 0xfa, 0xd1, 0xeb, 0x9e, 0x59, 0x4c, 0x32, 0xca, 0x65, 0x2c,
	0x16, 0x06, 0xe3, 0x59, 0x42, 0x85, 0x98, 0x61, 0x8c, 0x5a, 0x5a, 0x43, 0xe9, 0xa3, 0x35, 0x09,
	0x16, 0x56, 0x26, 0x19, 0x64, 0x39, 0x59, 0xf2, 0xf6, 0x7b, 0x1a, 0x7a, 0xda, 0x3f, 0xd4, 0xa4,
	0xa9, 0x49, 0x45, 0x7d, 0x6a, 0x41, 0x9f, 0x47, 0x54, 0xd4, 0x5d, 0x4a, 0x16, 0x28, 0x5e, 0xc7,
	0x0a, 0xad, 0x1c, 0x8b, 0x88, 0x4c, 0xda, 0xe5, 0x81, 0x26, 0xd2, 0x31, 0x8a, 0xe6, 0xa6, 0xe6,
	0x4f, 0xe2, 0xcf, 0x4f, 0x27, 0x1f, 0xcc, 0x3d, 0xb8, 0x1d, 0x44, 0xa6, 0x7d, 0xea, 0x85, 0xee,
	0xee, 0x80, 0x8e, 0xd8, 0x31, 0x3b, 0xdd, 0xbb, 0xf0, 0xa1, 0x2d, 0x83, 0xbe, 0x0c, 0x06, 0x3c,
	0xdc, 0x59, 0x7d, 0x05, 0xce, 0xf2, 0x3b, 0x60, 0x93, 0xcd, 0x33, 0xef, 0xda, 0xdd, 0x56, 0x32,
	0x96, 0x69, 0x84, 0xa3, 0x7f, 0x4d, 0xc3, 0x11, 0xb4, 0xba, 0x50, 0xeb, 0x42, 0xa7, 0x0b, 0x37,
	0x64, 0xd2, 0xf0, 0x7f, 0x5d, 0x30, 0xe9, 0xf9, 0xf0, 0x7e, 0x55, 0x72, 0xb6, 0x2e, 0x39, 0xfb,
	0x29, 0x39, 0x5b, 0x56, 0xdc, 0x59, 0x57, 0xdc, 0xf9, 0xac, 0xb8, 0xf3, 0x70, 0xa5, 0x8d, 0x7d,
	0x9e, 0x2b, 0x88, 0x28, 0x11, 0xd3, 0x6e, 0xa5, 0xf3, 0x3b, 0xb4, 0x6f, 0x94, 0xbf, 0x88, 0x61,
	0xe4, 0xf7, 0xcd, 0xcc, 0x76, 0x91, 0x61, 0xa1, 0xb6, 0x1a, 0xe9, 0xcb, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xc1, 0x7e, 0x76, 0x45, 0x88, 0x01, 0x00, 0x00,
}

func (m *DelegationTimestamp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegationTimestamp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegationTimestamp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Balance.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintDelegationTimestamp(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Timestamp):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintDelegationTimestamp(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintDelegationTimestamp(dAtA []byte, offset int, v uint64) int {
	offset -= sovDelegationTimestamp(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DelegationTimestamp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovDelegationTimestamp(uint64(l))
	l = m.Balance.Size()
	n += 1 + l + sovDelegationTimestamp(uint64(l))
	return n
}

func sovDelegationTimestamp(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDelegationTimestamp(x uint64) (n int) {
	return sovDelegationTimestamp(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DelegationTimestamp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDelegationTimestamp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegationTimestamp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegationTimestamp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationTimestamp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDelegationTimestamp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationTimestamp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDelegationTimestamp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDelegationTimestamp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDelegationTimestamp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Balance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDelegationTimestamp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDelegationTimestamp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDelegationTimestamp(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDelegationTimestamp
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDelegationTimestamp
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDelegationTimestamp
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDelegationTimestamp
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDelegationTimestamp
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDelegationTimestamp
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDelegationTimestamp        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDelegationTimestamp          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDelegationTimestamp = fmt.Errorf("proto: unexpected end of group")
)
