// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: temporal/icayieldmos/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a64e9c6b8c80d019, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a64e9c6b8c80d019, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetContractRemoteZoneRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetContractRemoteZoneRequest) Reset()         { *m = QueryGetContractRemoteZoneRequest{} }
func (m *QueryGetContractRemoteZoneRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetContractRemoteZoneRequest) ProtoMessage()    {}
func (*QueryGetContractRemoteZoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a64e9c6b8c80d019, []int{2}
}
func (m *QueryGetContractRemoteZoneRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetContractRemoteZoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetContractRemoteZoneRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetContractRemoteZoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetContractRemoteZoneRequest.Merge(m, src)
}
func (m *QueryGetContractRemoteZoneRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetContractRemoteZoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetContractRemoteZoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetContractRemoteZoneRequest proto.InternalMessageInfo

func (m *QueryGetContractRemoteZoneRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetContractRemoteZoneResponse struct {
	ContractRemoteZone ContractRemoteZone `protobuf:"bytes,1,opt,name=ContractRemoteZone,proto3" json:"ContractRemoteZone"`
}

func (m *QueryGetContractRemoteZoneResponse) Reset()         { *m = QueryGetContractRemoteZoneResponse{} }
func (m *QueryGetContractRemoteZoneResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetContractRemoteZoneResponse) ProtoMessage()    {}
func (*QueryGetContractRemoteZoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a64e9c6b8c80d019, []int{3}
}
func (m *QueryGetContractRemoteZoneResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetContractRemoteZoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetContractRemoteZoneResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetContractRemoteZoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetContractRemoteZoneResponse.Merge(m, src)
}
func (m *QueryGetContractRemoteZoneResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetContractRemoteZoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetContractRemoteZoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetContractRemoteZoneResponse proto.InternalMessageInfo

func (m *QueryGetContractRemoteZoneResponse) GetContractRemoteZone() ContractRemoteZone {
	if m != nil {
		return m.ContractRemoteZone
	}
	return ContractRemoteZone{}
}

type QueryAllContractRemoteZoneRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllContractRemoteZoneRequest) Reset()         { *m = QueryAllContractRemoteZoneRequest{} }
func (m *QueryAllContractRemoteZoneRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllContractRemoteZoneRequest) ProtoMessage()    {}
func (*QueryAllContractRemoteZoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a64e9c6b8c80d019, []int{4}
}
func (m *QueryAllContractRemoteZoneRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllContractRemoteZoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllContractRemoteZoneRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllContractRemoteZoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllContractRemoteZoneRequest.Merge(m, src)
}
func (m *QueryAllContractRemoteZoneRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllContractRemoteZoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllContractRemoteZoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllContractRemoteZoneRequest proto.InternalMessageInfo

func (m *QueryAllContractRemoteZoneRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllContractRemoteZoneResponse struct {
	ContractRemoteZone []ContractRemoteZone `protobuf:"bytes,1,rep,name=ContractRemoteZone,proto3" json:"ContractRemoteZone"`
	Pagination         *query.PageResponse  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllContractRemoteZoneResponse) Reset()         { *m = QueryAllContractRemoteZoneResponse{} }
func (m *QueryAllContractRemoteZoneResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllContractRemoteZoneResponse) ProtoMessage()    {}
func (*QueryAllContractRemoteZoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a64e9c6b8c80d019, []int{5}
}
func (m *QueryAllContractRemoteZoneResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllContractRemoteZoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllContractRemoteZoneResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllContractRemoteZoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllContractRemoteZoneResponse.Merge(m, src)
}
func (m *QueryAllContractRemoteZoneResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllContractRemoteZoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllContractRemoteZoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllContractRemoteZoneResponse proto.InternalMessageInfo

func (m *QueryAllContractRemoteZoneResponse) GetContractRemoteZone() []ContractRemoteZone {
	if m != nil {
		return m.ContractRemoteZone
	}
	return nil
}

func (m *QueryAllContractRemoteZoneResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "temporal.icayieldmos.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "temporal.icayieldmos.QueryParamsResponse")
	proto.RegisterType((*QueryGetContractRemoteZoneRequest)(nil), "temporal.icayieldmos.QueryGetContractRemoteZoneRequest")
	proto.RegisterType((*QueryGetContractRemoteZoneResponse)(nil), "temporal.icayieldmos.QueryGetContractRemoteZoneResponse")
	proto.RegisterType((*QueryAllContractRemoteZoneRequest)(nil), "temporal.icayieldmos.QueryAllContractRemoteZoneRequest")
	proto.RegisterType((*QueryAllContractRemoteZoneResponse)(nil), "temporal.icayieldmos.QueryAllContractRemoteZoneResponse")
}

func init() { proto.RegisterFile("temporal/icayieldmos/query.proto", fileDescriptor_a64e9c6b8c80d019) }

var fileDescriptor_a64e9c6b8c80d019 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x41, 0x6b, 0x13, 0x41,
	0x1c, 0xc5, 0x33, 0x31, 0xe6, 0x30, 0x82, 0x87, 0x31, 0x82, 0x84, 0xb0, 0xb6, 0x83, 0x68, 0x2d,
	0x3a, 0x43, 0xd2, 0x43, 0x8b, 0xb7, 0x56, 0xb0, 0x37, 0x69, 0x17, 0x4f, 0x3d, 0x58, 0x26, 0x9b,
	0x61, 0x1d, 0xba, 0xbb, 0xff, 0xed, 0xee, 0x44, 0x8d, 0xe2, 0x45, 0xfd, 0x00, 0x8a, 0xdf, 0x47,
	0x3c, 0xf6, 0x22, 0x14, 0xbc, 0x78, 0x12, 0x49, 0xfc, 0x20, 0x92, 0x99, 0x09, 0x4d, 0xd8, 0xcd,
	0x36, 0x82, 0xb7, 0x90, 0x7d, 0xef, 0xff, 0x7e, 0x6f, 0xe6, 0xbf, 0x8b, 0xd7, 0xb4, 0x8c, 0x53,
	0xc8, 0x44, 0xc4, 0x55, 0x20, 0x46, 0x4a, 0x46, 0x83, 0x18, 0x72, 0x7e, 0x3a, 0x94, 0xd9, 0x88,
	0xa5, 0x19, 0x68, 0x20, 0xad, 0x99, 0x82, 0xcd, 0x29, 0xda, 0xad, 0x10, 0x42, 0x30, 0x02, 0x3e,
	0xfd, 0x65, 0xb5, 0xed, 0x4e, 0x08, 0x10, 0x46, 0x92, 0x8b, 0x54, 0x71, 0x91, 0x24, 0xa0, 0x85,
	0x56, 0x90, 0xe4, 0xee, 0xe9, 0x7a, 0x69, 0x56, 0x2a, 0x32, 0x11, 0xcf, 0x24, 0xbc, 0x54, 0x12,
	0x40, 0xa2, 0x33, 0x11, 0xe8, 0xe3, 0x4c, 0xc6, 0xa0, 0xe5, 0xf1, 0x1b, 0x48, 0xa4, 0x33, 0x6c,
	0x06, 0x90, 0x4f, 0x25, 0x7d, 0x91, 0x4b, 0x8b, 0xcd, 0x5f, 0x76, 0xfb, 0x52, 0x8b, 0x2e, 0x4f,
	0x45, 0xa8, 0x12, 0x03, 0x60, 0xb5, 0xb4, 0x85, 0xc9, 0xe1, 0x54, 0x71, 0x60, 0x12, 0x7d, 0x79,
	0x3a, 0x94, 0xb9, 0xa6, 0x87, 0xf8, 0xc6, 0xc2, 0xbf, 0x79, 0x0a, 0x49, 0x2e, 0xc9, 0x23, 0xdc,
	0xb4, 0x64, 0xb7, 0xd0, 0x1a, 0xda, 0xb8, 0xd6, 0xeb, 0xb0, 0xb2, 0x73, 0x60, 0xd6, 0xb5, 0xd7,
	0x38, 0xfb, 0x75, 0xbb, 0xe6, 0x3b, 0x07, 0xdd, 0xc2, 0xeb, 0x66, 0xe4, 0xbe, 0xd4, 0x8f, 0x1d,
	0xba, 0x6f, 0xc8, 0x8f, 0x20, 0x91, 0x2e, 0x97, 0x5c, 0xc7, 0x75, 0x35, 0x30, 0xc3, 0x1b, 0x7e,
	0x5d, 0x0d, 0xe8, 0x47, 0x84, 0x69, 0x95, 0xcb, 0x71, 0x3d, 0xc7, 0xa4, 0xf8, 0xd4, 0x31, 0x6e,
	0x94, 0x33, 0x16, 0xf5, 0x8e, 0xb7, 0x64, 0x12, 0x3d, 0x71, 0xec, 0xbb, 0x51, 0xb4, 0x9c, 0xfd,
	0x09, 0xc6, 0x17, 0xa7, 0xeb, 0xc2, 0xef, 0x32, 0x7b, 0x15, 0x6c, 0x7a, 0x15, 0xcc, 0x6e, 0x90,
	0xbb, 0x0a, 0x76, 0x20, 0xc2, 0x99, 0xd7, 0x9f, 0x73, 0xd2, 0xef, 0xb3, 0xce, 0x4b, 0xd2, 0x2e,
	0xe9, 0x7c, 0xe5, 0xff, 0x74, 0x26, 0xfb, 0x0b, 0x75, 0xea, 0xa6, 0xce, 0xbd, 0x4b, 0xeb, 0x58,
	0xb8, 0xf9, 0x3e, 0xbd, 0xcf, 0x0d, 0x7c, 0xd5, 0xf4, 0x21, 0x1f, 0x10, 0x6e, 0xda, 0xdd, 0x20,
	0x4b, 0x08, 0x8b, 0xab, 0xd8, 0xbe, 0xbf, 0x82, 0xd2, 0xa6, 0xd2, 0x3b, 0xef, 0x7f, 0xfc, 0xf9,
	0x52, 0xf7, 0x48, 0x87, 0x57, 0xbc, 0x54, 0xe4, 0x1b, 0x2a, 0x3b, 0x39, 0xb2, 0x5d, 0x91, 0x53,
	0xb5, 0xb3, 0xed, 0x9d, 0x7f, 0x37, 0x3a, 0xde, 0x6d, 0xc3, 0xdb, 0x25, 0x7c, 0xf5, 0x37, 0x9c,
	0xbf, 0x55, 0x83, 0x77, 0xe4, 0x2b, 0xc2, 0x37, 0x8b, 0x73, 0x77, 0xa3, 0xa8, 0xb2, 0x45, 0xd5,
	0xf6, 0x56, 0xb6, 0xa8, 0x5c, 0x44, 0xda, 0x33, 0x2d, 0x1e, 0x90, 0xcd, 0xd5, 0x5b, 0xec, 0xf9,
	0x67, 0x63, 0x0f, 0x9d, 0x8f, 0x3d, 0xf4, 0x7b, 0xec, 0xa1, 0x4f, 0x13, 0xaf, 0x76, 0x3e, 0xf1,
	0x6a, 0x3f, 0x27, 0x5e, 0xed, 0x68, 0x27, 0x54, 0xfa, 0xc5, 0xb0, 0xcf, 0x02, 0x88, 0xf9, 0x33,
	0x37, 0xef, 0xe1, 0x53, 0xa9, 0x5f, 0x41, 0x76, 0x72, 0x11, 0xf0, 0x7a, 0x21, 0x42, 0x8f, 0x52,
	0x99, 0xf7, 0x9b, 0xe6, 0x83, 0xb6, 0xf5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x31, 0x4d, 0xd2,
	0xbe, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ContractRemoteZone items.
	ContractRemoteZone(ctx context.Context, in *QueryGetContractRemoteZoneRequest, opts ...grpc.CallOption) (*QueryGetContractRemoteZoneResponse, error)
	ContractRemoteZoneAll(ctx context.Context, in *QueryAllContractRemoteZoneRequest, opts ...grpc.CallOption) (*QueryAllContractRemoteZoneResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/temporal.icayieldmos.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ContractRemoteZone(ctx context.Context, in *QueryGetContractRemoteZoneRequest, opts ...grpc.CallOption) (*QueryGetContractRemoteZoneResponse, error) {
	out := new(QueryGetContractRemoteZoneResponse)
	err := c.cc.Invoke(ctx, "/temporal.icayieldmos.Query/ContractRemoteZone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ContractRemoteZoneAll(ctx context.Context, in *QueryAllContractRemoteZoneRequest, opts ...grpc.CallOption) (*QueryAllContractRemoteZoneResponse, error) {
	out := new(QueryAllContractRemoteZoneResponse)
	err := c.cc.Invoke(ctx, "/temporal.icayieldmos.Query/ContractRemoteZoneAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ContractRemoteZone items.
	ContractRemoteZone(context.Context, *QueryGetContractRemoteZoneRequest) (*QueryGetContractRemoteZoneResponse, error)
	ContractRemoteZoneAll(context.Context, *QueryAllContractRemoteZoneRequest) (*QueryAllContractRemoteZoneResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ContractRemoteZone(ctx context.Context, req *QueryGetContractRemoteZoneRequest) (*QueryGetContractRemoteZoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContractRemoteZone not implemented")
}
func (*UnimplementedQueryServer) ContractRemoteZoneAll(ctx context.Context, req *QueryAllContractRemoteZoneRequest) (*QueryAllContractRemoteZoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContractRemoteZoneAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.icayieldmos.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ContractRemoteZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetContractRemoteZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ContractRemoteZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.icayieldmos.Query/ContractRemoteZone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ContractRemoteZone(ctx, req.(*QueryGetContractRemoteZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ContractRemoteZoneAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllContractRemoteZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ContractRemoteZoneAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.icayieldmos.Query/ContractRemoteZoneAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ContractRemoteZoneAll(ctx, req.(*QueryAllContractRemoteZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "temporal.icayieldmos.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ContractRemoteZone",
			Handler:    _Query_ContractRemoteZone_Handler,
		},
		{
			MethodName: "ContractRemoteZoneAll",
			Handler:    _Query_ContractRemoteZoneAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "temporal/icayieldmos/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetContractRemoteZoneRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetContractRemoteZoneRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetContractRemoteZoneRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetContractRemoteZoneResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetContractRemoteZoneResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetContractRemoteZoneResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ContractRemoteZone.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllContractRemoteZoneRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllContractRemoteZoneRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllContractRemoteZoneRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllContractRemoteZoneResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllContractRemoteZoneResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllContractRemoteZoneResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ContractRemoteZone) > 0 {
		for iNdEx := len(m.ContractRemoteZone) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ContractRemoteZone[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetContractRemoteZoneRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetContractRemoteZoneResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ContractRemoteZone.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllContractRemoteZoneRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllContractRemoteZoneResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ContractRemoteZone) > 0 {
		for _, e := range m.ContractRemoteZone {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetContractRemoteZoneRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetContractRemoteZoneRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetContractRemoteZoneRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetContractRemoteZoneResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetContractRemoteZoneResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetContractRemoteZoneResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractRemoteZone", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ContractRemoteZone.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllContractRemoteZoneRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllContractRemoteZoneRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllContractRemoteZoneRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllContractRemoteZoneResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllContractRemoteZoneResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllContractRemoteZoneResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractRemoteZone", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractRemoteZone = append(m.ContractRemoteZone, ContractRemoteZone{})
			if err := m.ContractRemoteZone[len(m.ContractRemoteZone)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
