[[chains]]
id = 'uni-6'
rpc_addr = 'https://rpc.uni.junonetwork.io'
grpc_addr = 'http://juno-testnet-grpc.polkachu.com:12690'
websocket_addr = 'wss://uni-rpc.reece.sh/websocket'
rpc_timeout = '10s'
account_prefix = 'juno'
key_name = 'testkey'
store_prefix = 'ibc'
default_gas = 200000
max_gas = 3000000
gas_price = { price = 0.0025, denom = 'ujunox' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }