// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: temporal/compounder/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateCompoundSettings struct {
	Delegator         string              `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty"`
	ValidatorSettings []*ValidatorSetting `protobuf:"bytes,2,rep,name=validatorSettings,proto3" json:"validatorSettings,omitempty"`
	AmountToRemain    types.Coin          `protobuf:"bytes,3,opt,name=amountToRemain,proto3" json:"amountToRemain"`
	Frequency         *Frequency          `protobuf:"bytes,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
}

func (m *MsgCreateCompoundSettings) Reset()         { *m = MsgCreateCompoundSettings{} }
func (m *MsgCreateCompoundSettings) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCompoundSettings) ProtoMessage()    {}
func (*MsgCreateCompoundSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_577617f43b8ce0b3, []int{0}
}
func (m *MsgCreateCompoundSettings) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCompoundSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCompoundSettings.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCompoundSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCompoundSettings.Merge(m, src)
}
func (m *MsgCreateCompoundSettings) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCompoundSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCompoundSettings.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCompoundSettings proto.InternalMessageInfo

func (m *MsgCreateCompoundSettings) GetDelegator() string {
	if m != nil {
		return m.Delegator
	}
	return ""
}

func (m *MsgCreateCompoundSettings) GetValidatorSettings() []*ValidatorSetting {
	if m != nil {
		return m.ValidatorSettings
	}
	return nil
}

func (m *MsgCreateCompoundSettings) GetAmountToRemain() types.Coin {
	if m != nil {
		return m.AmountToRemain
	}
	return types.Coin{}
}

func (m *MsgCreateCompoundSettings) GetFrequency() *Frequency {
	if m != nil {
		return m.Frequency
	}
	return nil
}

type MsgCreateCompoundSettingsResponse struct {
}

func (m *MsgCreateCompoundSettingsResponse) Reset()         { *m = MsgCreateCompoundSettingsResponse{} }
func (m *MsgCreateCompoundSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCompoundSettingsResponse) ProtoMessage()    {}
func (*MsgCreateCompoundSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_577617f43b8ce0b3, []int{1}
}
func (m *MsgCreateCompoundSettingsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCompoundSettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCompoundSettingsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCompoundSettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCompoundSettingsResponse.Merge(m, src)
}
func (m *MsgCreateCompoundSettingsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCompoundSettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCompoundSettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCompoundSettingsResponse proto.InternalMessageInfo

type MsgUpdateCompoundSettings struct {
	Delegator         string              `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty"`
	ValidatorSettings []*ValidatorSetting `protobuf:"bytes,2,rep,name=validatorSettings,proto3" json:"validatorSettings,omitempty"`
	AmountToRemain    types.Coin          `protobuf:"bytes,3,opt,name=amountToRemain,proto3" json:"amountToRemain"`
	Frequency         *Frequency          `protobuf:"bytes,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
}

func (m *MsgUpdateCompoundSettings) Reset()         { *m = MsgUpdateCompoundSettings{} }
func (m *MsgUpdateCompoundSettings) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCompoundSettings) ProtoMessage()    {}
func (*MsgUpdateCompoundSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_577617f43b8ce0b3, []int{2}
}
func (m *MsgUpdateCompoundSettings) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCompoundSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCompoundSettings.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCompoundSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCompoundSettings.Merge(m, src)
}
func (m *MsgUpdateCompoundSettings) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCompoundSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCompoundSettings.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCompoundSettings proto.InternalMessageInfo

func (m *MsgUpdateCompoundSettings) GetDelegator() string {
	if m != nil {
		return m.Delegator
	}
	return ""
}

func (m *MsgUpdateCompoundSettings) GetValidatorSettings() []*ValidatorSetting {
	if m != nil {
		return m.ValidatorSettings
	}
	return nil
}

func (m *MsgUpdateCompoundSettings) GetAmountToRemain() types.Coin {
	if m != nil {
		return m.AmountToRemain
	}
	return types.Coin{}
}

func (m *MsgUpdateCompoundSettings) GetFrequency() *Frequency {
	if m != nil {
		return m.Frequency
	}
	return nil
}

type MsgUpdateCompoundSettingsResponse struct {
}

func (m *MsgUpdateCompoundSettingsResponse) Reset()         { *m = MsgUpdateCompoundSettingsResponse{} }
func (m *MsgUpdateCompoundSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCompoundSettingsResponse) ProtoMessage()    {}
func (*MsgUpdateCompoundSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_577617f43b8ce0b3, []int{3}
}
func (m *MsgUpdateCompoundSettingsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCompoundSettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCompoundSettingsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCompoundSettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCompoundSettingsResponse.Merge(m, src)
}
func (m *MsgUpdateCompoundSettingsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCompoundSettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCompoundSettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCompoundSettingsResponse proto.InternalMessageInfo

type MsgDeleteCompoundSettings struct {
	Delegator string `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty"`
}

func (m *MsgDeleteCompoundSettings) Reset()         { *m = MsgDeleteCompoundSettings{} }
func (m *MsgDeleteCompoundSettings) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteCompoundSettings) ProtoMessage()    {}
func (*MsgDeleteCompoundSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_577617f43b8ce0b3, []int{4}
}
func (m *MsgDeleteCompoundSettings) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteCompoundSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteCompoundSettings.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteCompoundSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteCompoundSettings.Merge(m, src)
}
func (m *MsgDeleteCompoundSettings) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteCompoundSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteCompoundSettings.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteCompoundSettings proto.InternalMessageInfo

func (m *MsgDeleteCompoundSettings) GetDelegator() string {
	if m != nil {
		return m.Delegator
	}
	return ""
}

type MsgDeleteCompoundSettingsResponse struct {
}

func (m *MsgDeleteCompoundSettingsResponse) Reset()         { *m = MsgDeleteCompoundSettingsResponse{} }
func (m *MsgDeleteCompoundSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteCompoundSettingsResponse) ProtoMessage()    {}
func (*MsgDeleteCompoundSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_577617f43b8ce0b3, []int{5}
}
func (m *MsgDeleteCompoundSettingsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteCompoundSettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteCompoundSettingsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteCompoundSettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteCompoundSettingsResponse.Merge(m, src)
}
func (m *MsgDeleteCompoundSettingsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteCompoundSettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteCompoundSettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteCompoundSettingsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateCompoundSettings)(nil), "temporal.compounder.MsgCreateCompoundSettings")
	proto.RegisterType((*MsgCreateCompoundSettingsResponse)(nil), "temporal.compounder.MsgCreateCompoundSettingsResponse")
	proto.RegisterType((*MsgUpdateCompoundSettings)(nil), "temporal.compounder.MsgUpdateCompoundSettings")
	proto.RegisterType((*MsgUpdateCompoundSettingsResponse)(nil), "temporal.compounder.MsgUpdateCompoundSettingsResponse")
	proto.RegisterType((*MsgDeleteCompoundSettings)(nil), "temporal.compounder.MsgDeleteCompoundSettings")
	proto.RegisterType((*MsgDeleteCompoundSettingsResponse)(nil), "temporal.compounder.MsgDeleteCompoundSettingsResponse")
}

func init() { proto.RegisterFile("temporal/compounder/tx.proto", fileDescriptor_577617f43b8ce0b3) }

var fileDescriptor_577617f43b8ce0b3 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x94, 0x41, 0xcb, 0xd3, 0x30,
	0x18, 0xc7, 0xdb, 0xb7, 0x2f, 0xc2, 0xf2, 0x82, 0x60, 0x15, 0xe9, 0x3b, 0x47, 0x9c, 0x1b, 0xc2,
	0x40, 0x48, 0xd9, 0x44, 0x41, 0xf0, 0xb4, 0x89, 0x9e, 0x76, 0xe9, 0xd4, 0x83, 0x17, 0xc9, 0xda,
	0xc7, 0x52, 0x68, 0x93, 0xda, 0x64, 0x63, 0xbb, 0xf9, 0x09, 0xc4, 0x8b, 0xdf, 0x69, 0xc7, 0x1d,
	0x3d, 0x89, 0x6c, 0x5f, 0x44, 0xd6, 0x35, 0x1d, 0x6e, 0xc9, 0x60, 0x77, 0x6f, 0x21, 0xf9, 0x3f,
	0xff, 0xfc, 0x9f, 0x5f, 0xc2, 0x83, 0x5a, 0x12, 0xb2, 0x9c, 0x17, 0x34, 0xf5, 0x43, 0x9e, 0xe5,
	0x7c, 0xc6, 0x22, 0x28, 0x7c, 0xb9, 0x20, 0x79, 0xc1, 0x25, 0x77, 0xef, 0xab, 0x53, 0x72, 0x38,
	0x6d, 0x3e, 0xd3, 0x95, 0xa8, 0xe5, 0x67, 0x01, 0x52, 0x26, 0x2c, 0x16, 0x7b, 0x87, 0x66, 0x57,
	0x27, 0xfe, 0x52, 0xc0, 0xd7, 0x19, 0xb0, 0x70, 0x59, 0x89, 0xb4, 0x8e, 0x73, 0x9a, 0x26, 0x11,
	0x95, 0xbc, 0x50, 0x96, 0x95, 0x18, 0x87, 0x5c, 0x64, 0x5c, 0xf8, 0x53, 0x2a, 0xc0, 0x9f, 0xf7,
	0xa7, 0x20, 0x69, 0xdf, 0x0f, 0x79, 0xc2, 0xaa, 0xf3, 0x07, 0x31, 0x8f, 0x79, 0xb9, 0xf4, 0x77,
	0xab, 0xfd, 0x6e, 0xe7, 0xe7, 0x15, 0xba, 0x1d, 0x8b, 0x78, 0x54, 0x00, 0x95, 0x30, 0xaa, 0x6e,
	0x99, 0x54, 0x59, 0xdd, 0x16, 0x6a, 0x44, 0x90, 0x42, 0xbc, 0xbb, 0xce, 0xb3, 0xdb, 0x76, 0xaf,
	0x11, 0x1c, 0x36, 0xdc, 0x09, 0xba, 0x57, 0x87, 0x51, 0x25, 0xde, 0x55, 0xdb, 0xe9, 0xdd, 0x0c,
	0x9e, 0x12, 0x0d, 0x21, 0xf2, 0xf1, 0x48, 0x1d, 0x9c, 0xd6, 0xbb, 0xef, 0xd0, 0x5d, 0x9a, 0xf1,
	0x19, 0x93, 0xef, 0x79, 0x00, 0x19, 0x4d, 0x98, 0xe7, 0xb4, 0xed, 0xde, 0xcd, 0xe0, 0x96, 0xec,
	0xfb, 0x23, 0xbb, 0xfe, 0x48, 0xd5, 0x1f, 0x19, 0xf1, 0x84, 0x0d, 0xaf, 0x57, 0xbf, 0x1f, 0x5b,
	0xc1, 0x51, 0x99, 0xfb, 0x1a, 0x35, 0x6a, 0x9e, 0xde, 0x75, 0xe9, 0x81, 0xb5, 0xa9, 0xde, 0x2a,
	0x55, 0x70, 0x28, 0xe8, 0x74, 0xd1, 0x13, 0x23, 0x96, 0x00, 0x44, 0xce, 0x99, 0x00, 0x05, 0xef,
	0x43, 0x1e, 0xfd, 0x87, 0x77, 0x0a, 0x4f, 0x8f, 0xa5, 0x86, 0xf7, 0xaa, 0x64, 0xf7, 0x06, 0x52,
	0xb8, 0x94, 0x5d, 0xe5, 0xaf, 0x2f, 0x55, 0xfe, 0x83, 0xef, 0x0e, 0x72, 0xc6, 0x22, 0x76, 0xbf,
	0xd9, 0xe8, 0xa1, 0xe1, 0x7b, 0x13, 0x6d, 0x4b, 0xc6, 0x77, 0x6f, 0xbe, 0xbc, 0x4c, 0xaf, 0xa2,
	0x94, 0x11, 0x0c, 0x9f, 0xc4, 0x18, 0x41, 0xaf, 0x37, 0x47, 0x38, 0x4f, 0xbb, 0x8c, 0x60, 0x60,
	0x6d, 0x8c, 0xa0, 0xd7, 0x9b, 0x23, 0x9c, 0x7f, 0x90, 0xe1, 0x8b, 0xd5, 0x06, 0xdb, 0xeb, 0x0d,
	0xb6, 0xff, 0x6c, 0xb0, 0xfd, 0x63, 0x8b, 0xad, 0xf5, 0x16, 0x5b, 0xbf, 0xb6, 0xd8, 0xfa, 0xf4,
	0xa8, 0x9e, 0x73, 0x8b, 0x7f, 0xc6, 0xed, 0x32, 0x07, 0x31, 0xbd, 0x53, 0x0e, 0xaa, 0xe7, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xfd, 0x60, 0x6a, 0x92, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateCompoundSettings(ctx context.Context, in *MsgCreateCompoundSettings, opts ...grpc.CallOption) (*MsgCreateCompoundSettingsResponse, error)
	UpdateCompoundSettings(ctx context.Context, in *MsgUpdateCompoundSettings, opts ...grpc.CallOption) (*MsgUpdateCompoundSettingsResponse, error)
	DeleteCompoundSettings(ctx context.Context, in *MsgDeleteCompoundSettings, opts ...grpc.CallOption) (*MsgDeleteCompoundSettingsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateCompoundSettings(ctx context.Context, in *MsgCreateCompoundSettings, opts ...grpc.CallOption) (*MsgCreateCompoundSettingsResponse, error) {
	out := new(MsgCreateCompoundSettingsResponse)
	err := c.cc.Invoke(ctx, "/temporal.compounder.Msg/CreateCompoundSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateCompoundSettings(ctx context.Context, in *MsgUpdateCompoundSettings, opts ...grpc.CallOption) (*MsgUpdateCompoundSettingsResponse, error) {
	out := new(MsgUpdateCompoundSettingsResponse)
	err := c.cc.Invoke(ctx, "/temporal.compounder.Msg/UpdateCompoundSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteCompoundSettings(ctx context.Context, in *MsgDeleteCompoundSettings, opts ...grpc.CallOption) (*MsgDeleteCompoundSettingsResponse, error) {
	out := new(MsgDeleteCompoundSettingsResponse)
	err := c.cc.Invoke(ctx, "/temporal.compounder.Msg/DeleteCompoundSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateCompoundSettings(context.Context, *MsgCreateCompoundSettings) (*MsgCreateCompoundSettingsResponse, error)
	UpdateCompoundSettings(context.Context, *MsgUpdateCompoundSettings) (*MsgUpdateCompoundSettingsResponse, error)
	DeleteCompoundSettings(context.Context, *MsgDeleteCompoundSettings) (*MsgDeleteCompoundSettingsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateCompoundSettings(ctx context.Context, req *MsgCreateCompoundSettings) (*MsgCreateCompoundSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCompoundSettings not implemented")
}
func (*UnimplementedMsgServer) UpdateCompoundSettings(ctx context.Context, req *MsgUpdateCompoundSettings) (*MsgUpdateCompoundSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompoundSettings not implemented")
}
func (*UnimplementedMsgServer) DeleteCompoundSettings(ctx context.Context, req *MsgDeleteCompoundSettings) (*MsgDeleteCompoundSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCompoundSettings not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateCompoundSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateCompoundSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateCompoundSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.compounder.Msg/CreateCompoundSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateCompoundSettings(ctx, req.(*MsgCreateCompoundSettings))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateCompoundSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateCompoundSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateCompoundSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.compounder.Msg/UpdateCompoundSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateCompoundSettings(ctx, req.(*MsgUpdateCompoundSettings))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteCompoundSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteCompoundSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteCompoundSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.compounder.Msg/DeleteCompoundSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteCompoundSettings(ctx, req.(*MsgDeleteCompoundSettings))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "temporal.compounder.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCompoundSettings",
			Handler:    _Msg_CreateCompoundSettings_Handler,
		},
		{
			MethodName: "UpdateCompoundSettings",
			Handler:    _Msg_UpdateCompoundSettings_Handler,
		},
		{
			MethodName: "DeleteCompoundSettings",
			Handler:    _Msg_DeleteCompoundSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "temporal/compounder/tx.proto",
}

func (m *MsgCreateCompoundSettings) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCompoundSettings) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCompoundSettings) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Frequency != nil {
		{
			size, err := m.Frequency.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.AmountToRemain.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.ValidatorSettings) > 0 {
		for iNdEx := len(m.ValidatorSettings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorSettings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Delegator) > 0 {
		i -= len(m.Delegator)
		copy(dAtA[i:], m.Delegator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Delegator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateCompoundSettingsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCompoundSettingsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCompoundSettingsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCompoundSettings) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCompoundSettings) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCompoundSettings) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Frequency != nil {
		{
			size, err := m.Frequency.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.AmountToRemain.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.ValidatorSettings) > 0 {
		for iNdEx := len(m.ValidatorSettings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorSettings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Delegator) > 0 {
		i -= len(m.Delegator)
		copy(dAtA[i:], m.Delegator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Delegator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCompoundSettingsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCompoundSettingsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCompoundSettingsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteCompoundSettings) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteCompoundSettings) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteCompoundSettings) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Delegator) > 0 {
		i -= len(m.Delegator)
		copy(dAtA[i:], m.Delegator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Delegator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteCompoundSettingsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteCompoundSettingsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteCompoundSettingsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateCompoundSettings) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Delegator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.ValidatorSettings) > 0 {
		for _, e := range m.ValidatorSettings {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = m.AmountToRemain.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.Frequency != nil {
		l = m.Frequency.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateCompoundSettingsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateCompoundSettings) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Delegator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.ValidatorSettings) > 0 {
		for _, e := range m.ValidatorSettings {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = m.AmountToRemain.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.Frequency != nil {
		l = m.Frequency.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateCompoundSettingsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteCompoundSettings) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Delegator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteCompoundSettingsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateCompoundSettings) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCompoundSettings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCompoundSettings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSettings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorSettings = append(m.ValidatorSettings, &ValidatorSetting{})
			if err := m.ValidatorSettings[len(m.ValidatorSettings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountToRemain", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountToRemain.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Frequency", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Frequency == nil {
				m.Frequency = &Frequency{}
			}
			if err := m.Frequency.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCompoundSettingsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCompoundSettingsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCompoundSettingsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCompoundSettings) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCompoundSettings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCompoundSettings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSettings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorSettings = append(m.ValidatorSettings, &ValidatorSetting{})
			if err := m.ValidatorSettings[len(m.ValidatorSettings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountToRemain", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountToRemain.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Frequency", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Frequency == nil {
				m.Frequency = &Frequency{}
			}
			if err := m.Frequency.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCompoundSettingsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCompoundSettingsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCompoundSettingsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteCompoundSettings) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteCompoundSettings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteCompoundSettings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteCompoundSettingsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteCompoundSettingsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteCompoundSettingsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
